### ISSUE TITLE
ROM disk broke wifi on PICO w

### ISSUE THREAD

**Issue by andreacampanella** [BlueSCSI/BlueSCSI-v2#163] opened 2024-07-13 11:59 UTC
I have no way to actually test this, but I recently uploaded the ROM file from the wiki on my pico w and it stopped connecting to the wifi, after a full firmware update the problem went away.

**Comment by erichelgeson** [comment] 2024-07-14 14:29
Duplicate of #98 - will be addressed with bootloader re-write. Sorry for the inconvenience.

**Closed by erichelgeson** 2024-07-14 14:29 UTC
